# Build settings

# theme: minima
include:
markdown: kramdown
permalink: :year/:title/

plugins:
  - jekyll-feed
  - jekyll-sitemap

include:
  - .htaccess

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README
  - Rakefile
  - bower_components
  - gulpfile.js
  - modernizr-config.json
  - node_modules
  - package.json