#------------------------------------------------------------
#
#  Config Settings
#
#------------------------------------------------------------

markdown: kramdown
permalink: :year/:title/

plugins:
  - jekyll-feed
  - jekyll-sitemap

include:
  - .htaccess

exclude:
  - LICENSE
  - README
  - Rakefile
  - bower_components
  - gulpfile.js
  - modernizr-config.json
  - node_modules
  - package.json